// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication56.Models
{
    public partial class Adjustmenttool
    {
        public int AdjId { get; set; }
        public string ToolName { get; set; }
        public int? Balance { get; set; }
        public int? ActualQuantity { get; set; }
        public int? Difference { get; set; }
        public string Because { get; set; }
        public bool Active { get; set; }  // New column



        public virtual Adjustment Adj { get; set; }
        public virtual Tool ToolNameNavigation { get; set; }
    }
}