// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication56.Models
{
    public partial class Adjustment
    {
        public Adjustment()
        {
            Adjustmenttools = new HashSet<Adjustmenttool>();
        }

        public int AdjId { get; set; }
        [DataType(DataType.Date)]
        public DateTime AdjDate { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }

        public virtual User EmailNavigation { get; set; }
        public virtual ICollection<Adjustmenttool> Adjustmenttools { get; set; }
    }
}