// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication56.Models
{
    public partial class Clinic
    {
        public Clinic()
        {
            Orders = new HashSet<Order>();
        }

        public string ClinicId { get; set; }
        public string ClinicName { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}