// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;

using System.Collections.Generic;

namespace WebApplication56.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderedTools = new HashSet<OrderedTool>();
        }

        [Key]
        public string OrdId { get; set; }
        [DataType(DataType.Date)]
        public DateTime OrdDate { get; set; }
        public string ClinicName { get; set; }
        public string Email { get; set; }
        public string Type { get; set; }
        public bool? Status { get; set; }

        public virtual Clinic ClinicNameNavigation { get; set; }
        public virtual User EmailNavigation { get; set; }
        public virtual ICollection<OrderedTool> OrderedTools { get; set; }
    }
}