// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication56.Models
{
    public partial class OrderedTool
    {
        public string OrdId { get; set; }
        public string ToolName { get; set; }
        public int? IncomingQuantity { get; set; }
        public int? OutgoingQuantity { get; set; }
        public int? Balance { get; set; }
        public bool? Status { get; set; }

        public virtual Order Ord { get; set; }
        public virtual Tool ToolNameNavigation { get; set; }
    }
}