// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication56.Models
{
    public partial class Tool
    {
        public Tool()
        {
            Adjustmenttools = new HashSet<Adjustmenttool>();
            OrderedTools = new HashSet<OrderedTool>();
        }

        public string ToolId { get; set; }
        public string ToolName { get; set; }
        public int? Balance { get; set; }
        public int? Storequantity { get; set; }
        public string Because { get; set; }

        public virtual ICollection<Adjustmenttool> Adjustmenttools { get; set; }
        public virtual ICollection<OrderedTool> OrderedTools { get; set; }
    }
}