// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication56.Models
{
    public partial class User
    {
        public User()
        {
            Adjustments = new HashSet<Adjustment>();
            Orders = new HashSet<Order>();
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public bool IsActive { get; set; } = true; // Default value to true
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}